### ISSUE TITLE
Need Turkish language

### ISSUE THREAD

**Issue by plato79** [blawar/translations#9]
Can you add Turkish translation also?

**Comment by plato79** [comment]
on second thought, nintendo doesn't actually support Turkish, I think it should support it for Tinfoil to show it..

**Comment by blawar** [comment]
just added it for you.  I can show the tinfoil UI in turkish, but not nintendo text.

**Comment by plato79** [comment]
Created [pull request](https://github.com/blawar/translations/pull/11)

There are at least two unconfirmed translations though because I'm not sure about their place in Tinfoil.

**Comment by blawar** [comment]
marged, thx.
